apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ca-root-cert
spec:
  isCA: true
  commonName: internal-ca
  secretName: ca-root-cert
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: selfsigned-ca
    kind: Issuer
