apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer
spec:
  template:
    spec:
      containers:
      - name: kube-rbac-proxy
        args:
          - --auth-header-fields-enabled
          - --secure-listen-address=0.0.0.0:8443
          - --upstream=http://127.0.0.1:8080/
          - --client-ca-file=/cert/consumer/tls.crt
          - --tls-cert-file=/cert/producer/tls.crt
          - --tls-private-key-file=/cert/producer/tls.key
          - --ignore-paths=/noauth
        image: quay.io/brancz/kube-rbac-proxy:v0.14.0
        volumeMounts:
          - name: consumer-cert
            mountPath: /cert/consumer
          - name: producer-cert
            mountPath: /cert/producer
        ports:
          - containerPort: 8443
            name: https
        resources:
          limits:
            cpu: 20m
            memory: 40Mi
          requests:
            cpu: 10m
            memory: 20Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          readOnlyRootFilesystem: true
          runAsGroup: 65532
          runAsNonRoot: true
          runAsUser: 65532
