apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer
spec:
  replicas: 1
  template:
    spec:
      serviceAccountName: producer
      automountServiceAccountToken: true
      containers:
      - name: web
        image: docker.io/traefik/whoami:latest
        env:
          - name: WHOAMI_PORT_NUMBER
            value: "8080"
        ports:
          - containerPort: 8080
            name: http
