apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: producer-cert
spec:
  isCA: true
  dnsNames:
    - producer
    - producer.rbac-proxy-example.svc
    - producer.rbac-proxy-example.svc.cluster.local
  secretName: producer-cert
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: internal-ca
    kind: Issuer
