apiVersion: v1
kind: Service
metadata:
  name: producer
spec:
  ports:
    - port: 8080
      protocol: TCP
      name: http
      targetPort: http
    - port: 8443
      protocol: TCP
      name: https
      targetPort: https
