apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer
spec:
  template:
    spec:
      volumes:
        - name: consumer-cert
          secret:
            secretName: consumer-cert

      containers:
      - name: consumer
        volumeMounts:
          - name: consumer-cert
            mountPath: /cert
        env:
          - name: HTTP_ENDPOINT
            value: https://producer:8443/example
          - name: HTTP_ENDPOINT_FORBIDDEN
            value: https://producer:8443/forbidden
          - name: HTTP_CACERT
            value: /cert/ca.crt
          - name: HTTP_CERT
            value: /cert/tls.crt
          - name: HTTP_KEY
            value: /cert/tls.key
