apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rbac-proxy-consumer
rules:
- apiGroups: ["security.openshift.io"]
  resourceNames:
    - anyuid
  resources:
    - securitycontextconstraints
  verbs:
    - use
- nonResourceURLs: ["/example"]
  verbs: ["get"]
