apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer
spec:
  replicas: 1
  template:
    spec:
      serviceAccountName: consumer
      automountServiceAccountToken: true
      terminationGracePeriodSeconds: 0
      containers:
      - name: consumer
        image: docker.io/alpine:latest
        env:
          - name: HTTP_ENDPOINT
            value: http://producer:8080
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          readOnlyRootFilesystem: false
          runAsUser: 0
        command:
          - sh
          - -c
          - |
            apk add curl

            if [ -n "$HTTP_TOKEN" ]; then
              token=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)
            fi

            echo "=== fetch /allowed ==="

            until curl -isf \
                ${HTTP_CACERT:+--cacert $HTTP_CACERT} \
                ${HTTP_CERT:+--cert $HTTP_CERT} \
                ${HTTP_KEY:+--key $HTTP_KEY} \
                ${token:+-H "Authorization: Bearer $token"} \
                "$HTTP_ENDPOINT"/allowed; do
              sleep 5
            done

            echo "=== fetch /forbidden ==="

            curl -is \
                ${HTTP_CACERT:+--cacert $HTTP_CACERT} \
                ${HTTP_CERT:+--cert $HTTP_CERT} \
                ${HTTP_KEY:+--key $HTTP_KEY} \
                ${token:+-H "Authorization: Bearer $token"} \
                "$HTTP_ENDPOINT"/forbidden

            echo "=== fetch /noauth ==="

            curl -is \
                ${HTTP_CACERT:+--cacert $HTTP_CACERT} \
                "$HTTP_ENDPOINT"/noauth

            echo "=== all done ==="

            sleep inf
