apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer
spec:
  template:
    spec:
      containers:
      - name: consumer
        env:
          - name: HTTP_ENDPOINT
            value: https://producer:8443
          - name: HTTP_CACERT
            value: /cert/producer/tls.crt
          - name: HTTP_TOKEN
            value: /var/run/secrets/kubernetes.io/serviceaccount/token
